services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fundraiser-app
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8080
    ports:
      - "8000:8080"
    volumes:
      - .:/var/www
    networks:
      - fundraiser-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: fundraiser-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - fundraiser-network

networks:
  fundraiser-network:
    driver: bridge

volumes:
  dbdata:
  